name: Docker CI/CD Pipeline


# specifies when the workflow is triggered 
on:
  push:
    branches:
      - dev

jobs:
  # Job to build and push the Docker image to dev
  push_image_dev:
    runs-on: ubuntu-latest 
    if: github.ref == 'refs/heads/dev' # Checks it the current branch is definitely dev
    services:
      docker:
        image: docker:20.10-dind # The docker in docker service is being used...
        options: --privileged #This flag here gives the containter extended priviledges...
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # use the custom built action from the actions marketplace to checkout the repository code 
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2 # uses the docker marketplace option to build a docker image
        
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        
      - name: List repository contents 
        run: | 
          echo "Listing the repository contents to confirm the context in which docker is building from"
          ls -R 

      - name: List the contents of the Dockefile that is building the image 
        run: | 
          cat Dockerfile

      - name: Build  Docker image to be uploaded to dev 
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE_DEV }}:latest . 

      - name: Push the Docker image to container registry
        run : |  
          docker push ${{ secrets.DOCKER_IMAGE_DEV }}:latest


  deploy_to_aws_ecr: 
    runs-on: ubuntu-latest 
    steps:
      - name: configure AWS Credentials 
        uses: aws-actions/configure-aws-credentials@v2 
        with: 
         aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY }}'
         aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
         aws-region: eu-west-2


      - name: Log into Amazon ECR
        run: >
          aws ecr get-login-password --region eu-west-2 | docker login
          --username AWS --password-stdin
          908395463728.dkr.ecr.eu-west-2.amazonaws.com

      - name: Checkout code
        uses: actions/checkout@v3 

      - name: Check what files are present 
        run: 'ls -R ${{github.workspace}}'

      - name: Build Docker image 
        run: docker build -t ci_image_test .

      - name: Tag image to enable the push to the repository
        run: docker tag ci_image_test:latest ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/ci_image:latest

      - name: Push the Image to the repository  
        run: docker push ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{secrets.AWS_REGION}}.amazonaws.com/ci_image:latest 

  # Job to build the Docker image for prod
  build_image_prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/prod'
    services:
      docker:
        image: docker:20.10-dind
        options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build Docker image for prod
        run: docker build -t ${{ secrets.DOCKER_IMAGE_PROD }}:latest .

